spring.config.import=optional:file:.env[.properties]

spring.application.name=ajudapp_api

server.port=8081

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=app
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=app

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/angular-app

logging.level.org.springframework.security=INFO

b2.s3.endpoint=${B2_S3_ENDPOINT}
b2.s3.region=${B2_S3_REGION}
b2.s3.access-key=${B2_S3_ACCESS_KEY}
b2.s3.secret-key=${B2_S3_SECRET_KEY}
b2.s3.bucket=${B2_S3_BUCKET}
